spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ControlTestSystemDB
    username: postgres
    password: 159357
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: 159357skui849rhDA07877rFG890hig68gu
  expiration: 86400000