openapi: "3.0.2"
info:
  title: "My API"
  description: "Get anything"
  version: "1.1"
  termsOfService: "https://terms"
  contact:
    name: "API"
    url: "https://api"
    email: "test@test.com"
  license:
    name: "CC"
    url: "https://price"
servers:
  - url: http://api/
    description: Production
  - url: http://beta/
    description: Other

